### ISSUE TITLE
Provide an option for storing user sessions

### ISSUE THREAD

**Issue by UJehle** [goat-community/goat#597] opened 2020-05-19 13:22 UTC
It would be nice if the users could store a session (calculations, scenarios, etc.) and continue to a later point of time. 
For this, a user login would be necessary. We can integrate the login-option for example in the bottom right corner. By clicking on the icon, a pop-up window for registration/log-in could open. 
![user_login](https://user-images.githubusercontent.com/49870195/82331208-1ad54880-99e4-11ea-868c-14f4d6da87b7.png)

In the backend, the user profiles and their sessions need to be stored in an extra table.

**Comment by EPajares** [comment] 2020-07-29 09:44
This issue is duplicate with this one: https://github.com/goat-community/goat/issues/50

**Comment by EPajares** [comment] 2020-07-29 09:46
This would be a major undertacking. The issue is not the client interaction but rather the fact the have to make sure that data of the users is persistantly stored and managed in the long-run. I would hesitate to do this anytime soon. I think for now it would be better to let the user import & export scenarios to derive the data.

**Comment by UJehle** [comment] 2020-08-03 08:29
Good point. Then let's put the focus on import & export.

**Comment by EPajares** [comment] 2020-10-27 09:37
I will close this one. As we have the issue for user management. As discussed at length this is something we should work on in the future :)

**Closed by EPajares** 2020-10-27 09:37 UTC
Labels: Database, Front-end, enhancement
