### ISSUE TITLE
PuT departures: Wrong visualization at München Hauptbahnhof?

### ISSUE THREAD

**Issue by UJehle** [goat-community/goat#1929] opened 2023-02-06 15:03 UTC
### Summary 📃

The PuT departures at the Munich main station (the one that is marked in red) seems faulty to me. Here, the pie is visualized in black + blue which means "train" + "bus".
![grafik](https://user-images.githubusercontent.com/49870195/217005205-a8ee238c-e0bd-4d8c-aa42-0492dcae2c3c.png)

But when I click on it, it either shows nothing ... 
![grafik](https://user-images.githubusercontent.com/49870195/217005319-e76708da-2f1e-453c-abb2-b5332b9ab189.png)

... or "tram" and "bus", which is not fitting to the colors of the pie chart.
![grafik](https://user-images.githubusercontent.com/49870195/217005440-bdd2cb2a-a3d8-4886-b90a-16ce7b509b36.png)

### Expected Behaviour ✔

see above

### Current Behaviour 🔦

see above

### Steps to reproduce 👣

1. Open GOAT Munich
2. Open indicator on public transport departures
3. select any day and time ( I picked sunday 07:00-09:00)

**Comment by EPajares** [comment] 2023-02-14 18:13
@Ebubeker maybe you can check this one

**Comment by Ebubeker** [comment] 2023-02-15 18:05
The problem is that we are currently only supporting 4 transport modes. bus, tram, subway and rail. There are more types of transport in the indicator so it throws an error when it doesn't find them.

**Comment by Ebubeker** [comment] 2023-02-17 16:56
@EPajares I added the translation so please make sure to not forget to add the German translation too in POEditor.

**Comment by EPajares** [comment] 2023-02-28 07:58
I merged it but currently the CI/CD does not deploy the new version. We need to check this and then can see the results online for testing

**Closed** 2023-03-15 07:46 UTC
Labels: Bug, Front-end
