### ISSUE TITLE
Kindergartens are shown twice

### ISSUE THREAD

**Issue by UJehle** [goat-community/goat#698] opened 2020-07-12 12:01 UTC
Some Kindergartens are displayed with 2 icons in GOAT. I guess this happens when the area and the building are tagged as "amenity=kindergarten". 
<img width="273" alt="kindergarten" src="https://user-images.githubusercontent.com/49870195/87245705-c8defb00-c447-11ea-8650-8c6df7600714.PNG">
some examples: 
Kindergarten St. Jakob, Freising
Haus des Kindes, Freising

**Comment by UJehle** [comment] 2020-07-12 12:33
one more example: Familienzentrum der Lebenshilfe im Steinpark, Asamstr. 19, 85356 Freising
(here, there is only one polygone (kindergarten area) and one point)

**Comment by EPajares** [comment] 2020-07-16 08:07
@rafleo2008

**Comment by rafleo2008** [comment] 2020-07-20 09:51
Fixed!, The problem will appear solved in the next commit

**Comment by UJehle** [comment] 2020-07-20 09:53
Awesome, thanks!

**Comment by UJehle** [comment] 2020-11-13 13:40
I just found some issues where we still have two POI icons for the same amenity:
https://www.openstreetmap.org/#map=18/48.12071/11.54938
![grafik](https://user-images.githubusercontent.com/49870195/99075356-a0b00600-25b9-11eb-80a8-5ed1c134cbe2.png)

https://www.openstreetmap.org/query?lat=48.16438&lon=11.55384
![grafik](https://user-images.githubusercontent.com/49870195/99075468-d359fe80-25b9-11eb-9056-f878e8f8cf05.png)

Is this just a problem of my local version or do you also have these duplicates @rafleo2008 ?

**Comment by UJehle** [comment] 2020-11-13 13:42
One more: 
https://www.openstreetmap.org/edit?editor=id&way=184872241#map=20/48.09265/11.65073
![grafik](https://user-images.githubusercontent.com/49870195/99078249-5aa97100-25be-11eb-865e-bb37a296f143.png)

**Comment by rafleo2008** [comment] 2020-11-15 12:07
Hello Ulrike,

Many thanks for this checking. Effectively, this is a global issue; we have not implemented any routine to clean duplicated POIS in primary_schools and secondary_schools before, but now, I have implemented a new function for check specific amenities called "clean_duplicated_amenities_in_pois", this will be applied in the main code to clean duplicated values in primary and secondary schools with a lookup radius of 40m.

With this change, I found 5 duplicated primary schools and 9 secondary schools that have been cleaned.

In the case of kindergartens, the problem was the lower value of the lookup radius "duplicated_kindergarten_lookup_radius", the variable was defined in 40 meters, but the kindergartens in the example were located at 49m, therefore, I have increased the variable to 50m to cover this case.

These changes will be available in the next PR.

**Comment by EPajares** [comment] 2020-11-15 13:37
Sounds great! Thanks @rafleo2008. There is a smaller issue when using the pois_rewrite function in the automated setup. 
The issue is that the function is using the buildings table but at this stage in the data preparation the table is not existing.
I uncommented it for now see here: https://github.com/goat-community/goat/commit/dabf2441e7bd87df4240f2d9b168030273133519

But I would like to finish this soon. So maybe let's discuss possible strategies to mitigate the issue. I think the best would be that the function is not snapping the points to the buildings.

**Comment by rafleo2008** [comment] 2020-11-15 13:41
You took my word, I'm doing the tests and just found that issue. I will disable the snapping in the function for now and we can discuss the possible solution this week.

**Comment by EPajares** [comment] 2020-11-15 19:54
Ok great! Thanks

**Comment by EPajares** [comment] 2020-11-17 22:31
I will close this issue now as it seems to be fixed at least for Munich. But with the help of the functions and setting the right radius this can be adjusted also to other cases.

**Closed by EPajares** 2020-11-17 22:31 UTC
Labels: Database
